scalar BigDecimal
scalar LocalDate

enum AssetType {
    ExchangeTradedFund
    MutualFund
    Debenture
}

interface Asset {
    id: ID!
    name: String!
    ticker: String!
    currentNav: BigDecimal!
}

type ExchangeTradedFund implements Asset {
    # Inherited fields
    id: ID!
    name: String!
    ticker: String!
    currentNav: BigDecimal!

    # Subclass-specific fields
    exchange: String!
    trackingError: BigDecimal!
}

type MutualFund implements Asset {
    # Inherited fields
    id: ID!
    name: String!
    ticker: String!
    currentNav: BigDecimal!

    # Subclass-specific fields
    fundCategory: String!
    expenseRatio: BigDecimal!
    exitLoad: BigDecimal!
}

type Debenture implements Asset {
    # Inherited fields
    id: ID!
    name: String!
    ticker: String!
    currentNav: BigDecimal!

    # Subclass-specific fields
    couponRate: BigDecimal!
    maturityDate: LocalDate!
}

type Owner {
    id: ID!
    aadhar: String!
    firstName: String!
    middleName: String
    lastName: String!
    pan: String!
    mobile: String!
    email: String!
}

type PortfolioHolding {
    id: ID!
    quantity: BigDecimal!
    averageBuyPrice: BigDecimal!
    asset: Asset!
}

type Portfolio {
    id: ID!
    totalValue: BigDecimal
    owner: Owner!
    portfolioHoldings: [PortfolioHolding!]!
}

type Query {
    getMarketAssets: [Asset!]!
    getPortfolioById(id: ID!): Portfolio
    getAssetByType(assetType: AssetType!): [Asset!]!
    getTopHoldings(portfolioId: ID!, limit: Int! = 5): [PortfolioHolding!]!
}
