spring:
  application:
    name: wealth-guard
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format_sql: true