#Global Properties
spring:
  application:
    name: wealth-guard
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
  graphql:
    http:
      path: /graphql
    schema-locations: classpath:schema.graphqls
---

#Development Properties
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      separator: "$$"
      data-locations: classpath:data-seeder.sql
  graphql:
    graphiql:
      enabled: true
      path: /graphiql